<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';
start_app_session();$token=(string)($_GET['token']??$_POST['token']??'');$invite=invitation_details($token);$error='';$registered=false;
if($invite){$check=app_db()->prepare('SELECT id FROM users WHERE email=?');$check->execute([$invite['email']]);$registered=(bool)$check->fetchColumn();}
if(empty($_SESSION['accept_invite_csrf']))$_SESSION['accept_invite_csrf']=bin2hex(random_bytes(32));
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals((string)$_SESSION['accept_invite_csrf'],(string)($_POST['csrf']??''))){http_response_code(403);exit('Sessão expirada. Atualize a página.');}
    if(!$invite)$error='Este convite expirou ou já foi utilizado.';
    else{$name=trim((string)($_POST['name']??''));$password=(string)($_POST['password']??'');if(!$registered&&strlen($password)<12)$error='Crie uma senha com pelo menos 12 caracteres.';else{try{$user=accept_team_invitation($token,$name,$password);session_regenerate_id(true);$_SESSION['affiliate_user']=$user;header('Location: dashboard.php');exit;}catch(DomainException $exception){$error=$exception->getMessage();}}}
}
function ie($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aceitar convite — Vértice</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/login.css"><link rel="stylesheet" href="assets/css/invitation.css"><link rel="manifest" href="/manifest.webmanifest"><meta name="theme-color" content="#176b50"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="apple-touch-icon" sizes="192x192" href="/assets/icons/icon-192.png"><link rel="stylesheet" href="/assets/css/pwa.css"><script src="/assets/js/pwa.js" defer></script></head><body><main class="layout"><section class="story"><div class="brand"><span class="mark">v</span> vértice<em>.</em></div><div class="copy"><div class="eyebrow">CONVITE PARA EQUIPE</div><h1>Vamos trabalhar<br>juntos.</h1><p><?php if($invite): ?>Você foi convidado para o espaço <b><?= ie($invite['tenant_name']) ?></b> como <?= ie(['admin'=>'administrador','manager'=>'gestor','viewer'=>'leitor'][$invite['role']]??'membro') ?>.<?php else: ?>O link não está disponível. Peça um novo convite ao administrador do espaço.<?php endif; ?></p></div></section><section class="form-side"><div class="form-wrap"><h2><?= $registered?'Aceitar convite':'Criar conta e aceitar' ?></h2><p class="sub"><?= $invite?ie($invite['email']):'Convite inválido' ?></p><?php if($error): ?><div class="message error" role="alert"><?= ie($error) ?></div><?php endif; ?><?php if($invite): ?><form method="post"><input type="hidden" name="csrf" value="<?= ie($_SESSION['accept_invite_csrf']) ?>"><input type="hidden" name="token" value="<?= ie($token) ?>"><?php if(!$registered): ?><div class="field"><label for="name">Seu nome</label><input id="name" name="name" autocomplete="name" required></div><?php endif; ?><div class="field"><label for="password"><?= $registered?'Senha atual da sua conta':'Crie uma senha (12 caracteres ou mais)' ?></label><input id="password" name="password" type="password" autocomplete="new-password" minlength="<?= $registered?'1':'12' ?>" required></div><button class="submit" type="submit">Aceitar convite →</button></form><?php endif; ?><div class="switch"><a href="login.php" class="link">Voltar para entrar</a></div></div></section></main></body></html>
