<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';
require_once __DIR__ . '/../modules/community-groups.php';
require_login(); start_app_session();
if(empty($_SESSION['community_manage_csrf']))$_SESSION['community_manage_csrf']=bin2hex(random_bytes(32));
$csrf=(string)$_SESSION['community_manage_csrf'];$error='';$flash='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Sessão expirada. Atualize a página e tente novamente.');}
    $action=(string)($_POST['action']??'');
    try{
        if($action==='create_group'){$pdo=app_db();$pdo->beginTransaction();try{$id=community_group_create($_POST);$token=community_group_issue_invite($id,(int)($_POST['invite_days']??30),isset($_POST['limit_uses'])&&$_POST['limit_uses']!==''?(int)$_POST['limit_uses']:null);$pdo->commit();$_SESSION['community_invite_once']=['group_id'=>$id,'token'=>$token];header('Location: communities.php?created=1');exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
        if($action==='issue_invite'){$pdo=app_db();$groupId=(string)($_POST['group_id']??'');$pdo->beginTransaction();try{community_group_revoke_invite($groupId);$token=community_group_issue_invite($groupId,(int)($_POST['invite_days']??30),isset($_POST['limit_uses'])&&$_POST['limit_uses']!==''?(int)$_POST['limit_uses']:null);$pdo->commit();$_SESSION['community_invite_once']=['group_id'=>$groupId,'token'=>$token];header('Location: communities.php?invite=1');exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
        if($action==='create_resource')community_resource_create($_POST);
        if($action==='toggle_group')community_group_toggle((string)($_POST['group_id']??''));
        if($action==='review')community_group_update_member((string)($_POST['group_id']??''),(string)($_POST['user_id']??''),(string)($_POST['status']??''));
        if($action==='revoke')community_group_revoke_invite((string)($_POST['group_id']??''));
        $flash='Alterações salvas.';
    }catch(DomainException $e){$error=$e->getMessage();}catch(Throwable $e){error_log('[AFFILIEY] community management failed: '.$e->getMessage());$error='Não foi possível concluir a ação. Tente novamente.';}
}
$groups=community_group_list_for_producer();$once=$_SESSION['community_invite_once']??null;unset($_SESSION['community_invite_once']);
function cg_e(mixed $value):string{return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Meus grupos — AFFILIEY</title><link rel="stylesheet" href="/assets/css/app-theme.css?v=3"><link rel="stylesheet" href="/assets/css/brand.css?v=affiliey4"><link rel="stylesheet" href="/assets/css/workspace-premium.css?v=3"><link rel="stylesheet" href="/assets/css/profile-environments.css?v=3"><link rel="stylesheet" href="/assets/css/typography.css?v=1"></head><body class="app-shell"><header class="topbar"><a class="brand" href="dashboard.php"><img class="brand-logo" src="/brand/affiliey-logo-dark.png" alt="AFFILIEY"></a><nav class="main-nav"><?= app_workspace_navigation() ?></nav><div class="top-actions"><?= app_header_account_tools() ?><span><?= cg_e(current_user()['name']??'') ?></span><a href="login.php?logout=1">Sair</a></div></header><main class="profile-page"><div class="profile-heading"><div><span class="profile-eyebrow">AMBIENTE DO PRODUTOR</span><h1>Meus grupos</h1><p>Crie comunidades e convide participantes para acessar o ambiente de aluno.</p></div></div>
<?php if($error): ?><p class="message error" role="alert"><?= cg_e($error) ?></p><?php endif; ?><?php if($flash||isset($_GET['created'])||isset($_GET['invite'])): ?><p class="message success" role="status"><?= cg_e($flash?:'Grupo atualizado.') ?></p><?php endif; ?>
<?php if(is_array($once)): $joinUrl=rtrim(app_public_url(),'/').'/group-join.php?token='.rawurlencode((string)$once['token']); ?><section class="profile-panel"><h2>Link de convite gerado</h2><p>Copie agora. Por segurança, o token não será exibido novamente depois que você sair desta página.</p><label>Convite<input readonly value="<?= cg_e($joinUrl) ?>" onclick="this.select()"></label></section><?php endif; ?>
<section class="profile-panel"><div class="profile-panel-head"><div><h2>Grupos ativos</h2><p><?= count($groups) ?> grupo(s) nesta organização</p></div></div><?php if(!$groups): ?><p class="profile-muted">Você ainda não criou um grupo. Comece no formulário abaixo.</p><?php else: ?><div class="profile-resource-list"><?php foreach($groups as $group): $pending=community_group_pending_members((string)$group['id']); $activeMembers=community_group_active_members((string)$group['id']); ?><article><div><span class="profile-product-platform"><?= $group['join_policy']==='approval'?'ENTRADA COM APROVAÇÃO':'ENTRADA AUTOMÁTICA' ?> · <?= (int)$group['member_count'] ?> participante(s)</span><h3><?= cg_e($group['name']) ?></h3><p><?= nl2br(cg_e($group['description'])) ?></p><?php if($pending): ?><h4>Solicitações pendentes (<?= count($pending) ?>)</h4><?php foreach($pending as $member): ?><div class="profile-group-member"><span><?= cg_e($member['name']) ?> · <?= cg_e($member['email']) ?></span><form method="post"><input type="hidden" name="csrf" value="<?= cg_e($csrf) ?>"><input type="hidden" name="action" value="review"><input type="hidden" name="group_id" value="<?= cg_e($group['id']) ?>"><input type="hidden" name="user_id" value="<?= cg_e($member['user_id']) ?>"><button name="status" value="active" type="submit">Aprovar</button><button name="status" value="rejected" type="submit">Recusar</button></form></div><?php endforeach; ?><?php endif; ?><?php if($activeMembers): ?><h4>Participantes ativos (<?= count($activeMembers) ?>)</h4><?php foreach($activeMembers as $member): ?><div class="profile-group-member"><span><?= cg_e($member['name']) ?> · <?= cg_e($member['email']) ?></span><span>Participante</span></div><?php endforeach; ?><?php endif; ?><form method="post" class="community-invite-form"><input type="hidden" name="csrf" value="<?= cg_e($csrf) ?>"><input type="hidden" name="action" value="issue_invite"><input type="hidden" name="group_id" value="<?= cg_e($group['id']) ?>"><label>Validade em dias<input type="number" name="invite_days" min="1" max="365" value="30"></label><label>Limite de usos<input type="number" name="limit_uses" min="1" placeholder="Sem limite"></label><button class="button primary" type="submit">Gerar novo convite</button></form></div></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="profile-panel"><div class="profile-panel-head"><div><h2>Criar grupo</h2><p>Convites são individuais por token e podem ser revogados gerando outro link.</p></div></div><?php if(app_user_can('communities','create')): ?><form method="post" class="community-form"><input type="hidden" name="csrf" value="<?= cg_e($csrf) ?>"><input type="hidden" name="action" value="create_group"><label>Nome<input name="name" maxlength="160" required></label><label>Ingresso<select name="join_policy"><option value="automatic">Aprovação automática</option><option value="approval">Solicitar aprovação</option></select></label><label>Descrição<textarea name="description" maxlength="5000" rows="3"></textarea></label><label>Imagem de capa (HTTPS)<input type="url" name="cover_url" placeholder="https://..."></label><label>Validade do convite (dias)<input type="number" name="invite_days" min="1" max="365" value="30"></label><label>Limite de usos<input type="number" name="limit_uses" min="1" placeholder="Sem limite"></label><button class="button primary" type="submit">Criar grupo e gerar convite</button></form><?php else: ?><p class="profile-muted">Seu papel pode visualizar grupos, mas não criar.</p><?php endif; ?></section></main></body></html>
