<?php
declare(strict_types=1);
require_once __DIR__.'/../modules/auth.php';require_once __DIR__.'/../modules/affiliate-community.php';require_once __DIR__.'/../modules/affiliate-groups.php';require_once __DIR__.'/../modules/affiliates.php';require_login();start_app_session();if(empty($_SESSION['events_csrf']))$_SESSION['events_csrf']=bin2hex(random_bytes(32));$csrf=(string)$_SESSION['events_csrf'];$error='';$flash='';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($csrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Sessão expirada. Atualize a página.');}try{if(!app_user_can('events','create'))throw new DomainException('Sem permissão para agendar eventos.');affiliate_event_save($_POST,(string)current_user()['id']);$flash='Reunião agendada e publicada para o público escolhido.';}catch(DomainException $e){$error=$e->getMessage();}catch(Throwable $e){$error='Não foi possível salvar o evento.';error_log('[AFFILIEY] events: '.$e->getMessage());}}
$events=affiliate_event_list();$affiliates=affiliate_read_all();$groups=affiliate_group_list();function ev_e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reuniões — AFFILIEY</title><link rel="stylesheet" href="/assets/css/app-theme.css?v=3"><link rel="stylesheet" href="/assets/css/brand.css?v=affiliey4"><link rel="stylesheet" href="/assets/css/profile-environments.css?v=1"><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/brand/affiliey-favicon.png"></head><body class="app-shell"><header class="topbar"><a class="brand" href="dashboard.php"><img class="brand-logo" src="/brand/affiliey-logo-dark.png" alt="AFFILIEY"></a><nav class="main-nav"><?= app_workspace_navigation() ?></nav><div class="top-actions"><?= app_header_account_tools() ?><span><?= ev_e(current_user()['name']??'') ?></span><a href="login.php?logout=1">Sair</a></div></header><main class="profile-page"><div class="profile-heading"><div><span class="profile-eyebrow">DESENVOLVIMENTO DA REDE</span><h1>Reuniões e treinamentos</h1><p>Agende encontros e compartilhe links com a rede ou segmentos específicos.</p></div></div><?php if($error): ?><p class="message error" role="alert"><?= ev_e($error) ?></p><?php endif; ?><?php if($flash): ?><p class="message success" role="status"><?= ev_e($flash) ?></p><?php endif; ?>
<?php if(app_user_can('events','create')): ?><section class="profile-panel"><div class="profile-panel-head"><div><h2>Agendar encontro</h2><p>O endereço da reunião deve usar HTTPS.</p></div></div><form method="post" class="community-form"><input type="hidden" name="csrf" value="<?= ev_e($csrf) ?>"><label>Título<input name="title" maxlength="160" required></label><label>Data e hora<input name="starts_at" type="datetime-local" required></label><label>Link da reunião<input name="url" type="url" maxlength="2000" placeholder="https://..." required></label><label>Descrição<textarea name="description" maxlength="4000" rows="3"></textarea></label><label>Público<select name="audience_type"><option value="all">Toda a rede</option><option value="group">Um grupo</option><option value="affiliate">Um afiliado</option></select></label><label>Grupo<select name="group"><option value="">Selecione</option><?php foreach($groups as $g): ?><option value="<?= ev_e($g['name']) ?>"><?= ev_e($g['name']) ?></option><?php endforeach; ?></select></label><label>Afiliado<select name="affiliate_id"><option value="">Selecione</option><?php foreach($affiliates as $a): if($a['status']!=='active')continue; ?><option value="<?= ev_e($a['id']) ?>"><?= ev_e($a['name']) ?></option><?php endforeach; ?></select></label><button class="button primary" type="submit">Agendar reunião</button></form></section><?php endif; ?>
<section class="profile-panel"><div class="profile-panel-head"><div><h2>Agenda da organização</h2><p>Eventos publicados e confirmações registradas.</p></div></div><?php if(!$events): ?><p class="profile-muted">Nenhuma reunião agendada.</p><?php else: ?><div class="profile-resource-list"><?php foreach($events as $event): ?><article><div><span class="profile-product-platform"><?= ev_e(['all'=>'Toda a rede','group'=>'Grupo · '.$event['audience_group'],'affiliate'=>'Afiliado'][$event['audience_type']]??$event['audience_type']) ?></span><h3><?= ev_e($event['title']) ?></h3><p><?= ev_e(date('d/m/Y H:i',strtotime($event['starts_at']))) ?> · <?= ev_e($event['description']) ?></p><a href="<?= ev_e($event['meeting_url']) ?>" target="_blank" rel="noopener noreferrer">Abrir reunião ↗</a></div></article><?php endforeach; ?></div><?php endif; ?></section></main></body></html>
