<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';
require_once __DIR__ . '/../modules/integrations.php';
require_login();
require_role(['owner', 'admin']);
start_app_session();

if (empty($_SESSION['integrations_csrf'])) $_SESSION['integrations_csrf'] = bin2hex(random_bytes(32));
$csrf = $_SESSION['integrations_csrf'];
$error = $flash = $oneTimeSecret = '';
$createdId = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!hash_equals($csrf, (string)($_POST['csrf'] ?? ''))) { http_response_code(403); exit('Sessão expirada. Atualize a página.'); }
    try {
        $action = (string)($_POST['action'] ?? '');
        if ($action === 'create') {
            $connection = integration_create((string)($_POST['name'] ?? ''), (string)($_POST['platform'] ?? 'kiwify'), (string)($_POST['platform_secret'] ?? $_POST['hottok'] ?? ''));
            $oneTimeSecret = (string)$connection['token'];
            $createdId = (string)$connection['id'];
            $flash = match ($connection['platform']) { 'hotmart' => 'Conexão Hotmart criada. O Hottok foi armazenado com segurança.', 'eduzz' => 'Conexão Eduzz criada. A chave de assinatura foi armazenada com segurança.', default => 'Conexão Kiwify criada. Copie o segredo agora; ele não será exibido novamente.' };
        } elseif (in_array($action, ['toggle', 'rotate'], true)) {
            $oneTimeSecret = integration_change((string)($_POST['id'] ?? ''), $action) ?? '';
            $flash = $action === 'rotate' ? 'Segredo renovado. Atualize o webhook na Kiwify.' : 'Status da conexão atualizado.';
        } else $error = 'Ação inválida.';
    } catch (DomainException $e) { $error = $e->getMessage(); }
    catch (Throwable $e) { $error = 'Não foi possível atualizar a integração.'; }
}
$connections = integration_list();
$eventsStmt = app_db()->prepare('SELECT e.event_type,e.result,e.message,e.created_at,c.name AS connection_name,c.platform FROM integration_events e JOIN integration_connections c ON c.id=e.connection_id WHERE e.tenant_id=? ORDER BY e.created_at DESC LIMIT 30');
$eventsStmt->execute([tenant_id()]); $events = $eventsStmt->fetchAll();
$https = !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off';
$origin = ($https ? 'https://' : 'http://') . ($_SERVER['HTTP_HOST'] ?? 'localhost');
$baseUrl = $origin . '/webhook.php';
function ine($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Integrações — AFFILIEY</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/integrations.css"><script src="assets/js/integrations.js" defer></script><link rel="stylesheet" href="assets/css/app-theme.css?v=3"><link rel="manifest" href="/manifest.webmanifest"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="apple-touch-icon" sizes="180x180" href="/brand/affiliey-apple-touch-icon.png"><link rel="stylesheet" href="/assets/css/pwa.css"><script src="/assets/js/pwa.js" defer></script><link rel="icon" type="image/png" href="/brand/affiliey-favicon.png"><link rel="stylesheet" href="/assets/css/brand.css?v=affiliey4"><link rel="stylesheet" href="/assets/css/workspace-premium.css?v=1"><meta name="theme-color" content="#111827"><meta property="og:site_name" content="AFFILIEY"><meta name="description" content="Gestão de afiliados, vendas, metas e campanhas em uma plataforma."><meta property="og:description" content="Gestão de afiliados, vendas, metas e campanhas em uma plataforma."><meta property="og:type" content="website"><meta property="og:title" content="AFFILIEY | Plataforma de afiliados"><meta property="og:image" content="https://afiliados.horizoncafe.com.br/brand/affiliey-logo-light.png"><link rel="stylesheet" href="/assets/css/page-transitions.css?v=1"><script src="/assets/js/page-transitions.js" defer></script><link rel="stylesheet" href="/assets/css/integrations-premium.css?v=1"></head><body class="app-shell">
<header class="topbar"><a class="brand" href="dashboard.php"><picture class="brand-picture"><source media="(max-width: 640px)" srcset="/brand/affiliey-symbol.png"><img class="brand-logo" src="/brand/affiliey-logo-dark.png" alt="AFFILIEY"></picture></a><nav class="main-nav"><a href="dashboard.php">Visão geral</a><a href="affiliates.php">Afiliados</a><a href="sales.php">Vendas</a><a href="campaigns.php">Metas</a><a href="ranking.php">Ranking</a><a href="rewards.php">Recompensas</a><a href="announcements.php">Comunicados</a><a href="team.php">Equipe</a><a class="selected" href="integrations.php">Integrações</a></nav><div class="top-actions"><span><?= ine(current_user()['name'] ?? '') ?></span><a href="login.php?logout=1">Sair</a></div></header>
<main class="page integrations-page"><div class="crumb"><a href="dashboard.php">Workspace</a> / Integrações</div><section class="welcome"><div><span class="eyebrow">DADOS DE VENDAS CONECTADOS</span><h1>Integrações</h1><p>Receba eventos da Kiwify, Hotmart e Eduzz e acompanhe as vendas em um só lugar.</p></div><div class="provider-set" aria-label="Plataformas disponíveis"><span><i>K</i>Kiwify</span><span><i>H</i>Hotmart</span><span><i>E</i>Eduzz</span></div></section><section class="integration-flow" aria-label="Fluxo de vendas integrado"><div class="flow-platforms"><span class="flow-kicker">FONTES DE VENDA</span><strong>Kiwify <i>K</i></strong><strong>Hotmart <i>H</i></strong><strong>Eduzz <i>E</i></strong></div><div class="flow-connector" aria-hidden="true"><span></span><span></span><span></span></div><div class="flow-center"><span class="flow-symbol">AF</span><span><b>AFFILIEY HUB</b><small>Eventos seguros em um só lugar</small></span></div><div class="flow-connector" aria-hidden="true"><span></span><span></span><span></span></div><div class="flow-output"><span class="flow-output-icon" aria-hidden="true">↗</span><span><b>VENDAS ATRIBUÍDAS</b><small>Dashboard · ranking · comissões</small></span></div></section><?php if ($flash): ?><div class="notice success"><?= ine($flash) ?></div><?php endif; ?><?php if ($error): ?><div class="notice error"><?= ine($error) ?></div><?php endif; ?>
<?php if ($oneTimeSecret !== ''): ?><section class="secret-box"><b>Segredo Kiwify — copie agora</b><p>Configure este segredo no webhook da Kiwify. Por segurança, não será exibido novamente.</p><div class="copy-row"><input id="secretValue" readonly value="<?= ine($oneTimeSecret) ?>"><button class="button primary" type="button" data-copy="secretValue">Copiar segredo</button></div></section><?php endif; ?>
<div class="integration-grid"><section class="panel setup-panel"><div class="panel-heading"><div><h2>Conectar plataforma</h2><p>Importe vendas por webhooks autenticados.</p></div><span class="kiwify-icon">↗</span></div>
<form method="post" class="create-form"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="create"><label>Plataforma<select id="platformSelect" name="platform"><option value="kiwify">Kiwify</option><option value="hotmart">Hotmart</option><option value="eduzz">Eduzz</option></select></label><label>Nome para identificar a conta<input name="name" maxlength="80" placeholder="Ex.: Minha loja" required></label><label id="providerSecretField" hidden><span id="providerSecretLabel">Credencial</span><input id="providerSecretInput" name="hottok" type="password" maxlength="255" autocomplete="off" placeholder="Cole a credencial do webhook"><small id="providerSecretHelp">A credencial é criptografada e não volta a ser exibida.</small></label><button class="button primary" type="submit">＋ Criar conexão</button></form>
<div class="steps" data-platform-instructions="kiwify"><h3>Configurar a Kiwify</h3><ol><li>Crie a conexão; o AFFILIEY gera um segredo para assinar os eventos.</li><li>Na Kiwify, abra Apps → Webhooks, selecione os produtos e eventos de venda aprovada, reembolso e chargeback.</li><li>Cadastre o endereço do receptor e o segredo exibido após criar a conexão.</li></ol><div class="endpoint-preview"><small>Formato do endereço</small><code><?= ine($baseUrl) ?>?connection=ID_DA_CONEXAO&amp;signature=ASSINATURA_KIWIFY</code></div></div>
<div class="steps" data-platform-instructions="hotmart" hidden><h3>Configurar a Hotmart</h3><ol><li>Na Hotmart, abra Ferramentas → Webhook e crie uma configuração na versão 2.0.0.</li><li>Use o endereço específico da conexão, mostrado na lista ao lado, e selecione eventos de compra aprovada, reembolso, chargeback e cancelamento.</li><li>Copie o Hottok da configuração da Hotmart e cole no formulário acima antes de criar a conexão.</li><li>No cadastro do afiliado, informe o código <code>affiliate_code</code> da Hotmart para atribuir as vendas automaticamente.</li></ol><p>O AFFILIEY valida o cabeçalho <code>X-HOTMART-HOTTOK</code> antes de registrar pedidos.</p></div>
<div class="steps" data-platform-instructions="eduzz" hidden><h3>Configurar a Eduzz</h3><ol><li>No Console do Desenvolvedor da Eduzz, crie uma chave de segurança para assinar o webhook e use a mesma chave neste formulário.</li><li>Crie o webhook para o endereço desta conexão e selecione os eventos de fatura paga, reembolsada, chargeback e cancelada.</li><li>As vendas serão relacionadas ao afiliado pelo e-mail recebido no evento.</li></ol><p>O AFFILIEY confere a assinatura <code>x-signature</code> HMAC-SHA256 do corpo original antes de processar.</p></div>
<?php if (!$https): ?><div class="warning">Este endereço está em HTTP. Para receber webhooks externos, publique o sistema em um domínio com HTTPS.</div><?php endif; ?></section>
<section class="panel connection-panel"><div class="panel-heading"><div><h2>Suas conexões</h2><p><?= count($connections) ?> conexão(ões) neste espaço</p></div></div><?php if (!$connections): ?><div class="empty-state"><span>↗</span><b>Nenhuma conexão ainda</b><small>Crie uma conexão Kiwify, Hotmart ou Eduzz para começar.</small></div><?php endif; ?>
<?php foreach ($connections as $connection): $platform = (string)$connection['platform']; $platformLabel = ['kiwify'=>'Kiwify','hotmart'=>'Hotmart','eduzz'=>'Eduzz'][$platform] ?? ucfirst($platform); $platformMark = ['kiwify'=>'K','hotmart'=>'H','eduzz'=>'E'][$platform] ?? '?'; $isHotmart = $platform === 'hotmart'; $needsQuerySignature = $platform === 'kiwify'; $endpoint = $baseUrl . '?connection=' . rawurlencode($connection['id']) . ($needsQuerySignature ? '&signature=ASSINATURA_KIWIFY' : ''); ?>
<article class="connection"><div class="connection-title"><span class="kiwify-icon"><?= ine($platformMark) ?></span><span><b><?= ine($connection['name']) ?></b><small><?= ine($platformLabel) ?> · <?= $connection['status'] === 'active' ? 'Recebendo eventos' : 'Pausada' ?></small></span><span class="state <?= ine($connection['status']) ?>"><?= $connection['status'] === 'active' ? 'Ativa' : 'Pausada' ?></span></div><div class="connection-stats"><span><b><?= (int)$connection['event_count'] ?></b> eventos</span><span><b><?= (int)$connection['order_count'] ?></b> pedidos</span><span>Último evento: <b><?= $connection['last_event_at'] ? ine(date('d/m/Y H:i', strtotime($connection['last_event_at']))) : '—' ?></b></span></div><div class="endpoint-line"><input readonly value="<?= ine($endpoint) ?>"><button type="button" class="button" data-copy-input>Copiar URL</button></div><div class="connection-actions"><form method="post"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= ine($connection['id']) ?>"><button class="text-button" type="submit"><?= $connection['status'] === 'active' ? 'Pausar' : 'Reativar' ?></button></form><?php if ($platform === 'kiwify'): ?><form method="post" onsubmit="return confirm('O segredo antigo deixará de funcionar. Atualize o webhook na Kiwify. Continuar?')"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="rotate"><input type="hidden" name="id" value="<?= ine($connection['id']) ?>"><button class="text-button" type="submit">Renovar segredo</button></form><?php endif; ?></div></article><?php endforeach; ?></section></div>
<section class="panel log-panel"><div class="panel-heading"><div><h2>Eventos recebidos</h2><p>Últimos 30 eventos. Payloads brutos não são armazenados.</p></div></div><div class="table-scroll"><table><thead><tr><th>Horário</th><th>Plataforma / conexão</th><th>Evento</th><th>Resultado</th><th>Detalhe</th></tr></thead><tbody><?php if (!$events): ?><tr><td colspan="5" class="empty">Ainda não recebemos eventos.</td></tr><?php endif; ?><?php foreach ($events as $event): ?><tr><td><?= ine(date('d/m/Y H:i', strtotime($event['created_at']))) ?></td><td><?= ine(ucfirst($event['platform']) . ' · ' . $event['connection_name']) ?></td><td><code><?= ine($event['event_type']) ?></code></td><td><span class="result <?= ine($event['result']) ?>"><?= ine($event['result']) ?></span></td><td><?= ine($event['message'] ?: 'Processado') ?></td></tr><?php endforeach; ?></tbody></table></div></section><p class="footnote">Hotmart usa o código externo do afiliado cadastrado no perfil; Eduzz usa o e-mail do afiliado enviado no evento. Pedidos sem correspondência entram sem atribuição.</p></main></body></html>
