<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';
require_once __DIR__ . '/../modules/integrations.php';
require_once __DIR__ . '/../modules/affiliates.php';
require_login();
require_role(['owner', 'admin']);
start_app_session();

if (empty($_SESSION['integrations_csrf'])) $_SESSION['integrations_csrf'] = bin2hex(random_bytes(32));
$csrf = $_SESSION['integrations_csrf'];
$error = $flash = $oneTimeSecret = '';
$createdId = $oneTimePlatform = $oneTimeWebhookUrl = '';
$https = !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off';
$origin = ($https ? 'https://' : 'http://') . ($_SERVER['HTTP_HOST'] ?? 'localhost');
$baseUrl = $origin . '/webhook.php';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!hash_equals($csrf, (string)($_POST['csrf'] ?? ''))) { http_response_code(403); exit('Sessão expirada. Atualize a página.'); }
    try {
        $action = (string)($_POST['action'] ?? '');
        if ($action === 'create') {
            $connection = integration_create((string)($_POST['name'] ?? ''), (string)($_POST['platform'] ?? 'kiwify'), (string)($_POST['platform_secret'] ?? $_POST['hottok'] ?? ''));
            $oneTimeSecret = (string)$connection['token'];
            $createdId = (string)$connection['id'];
            $oneTimePlatform = (string)$connection['platform'];
            if ($oneTimePlatform === 'applyfy') $oneTimeWebhookUrl = $baseUrl . '?connection=' . rawurlencode($createdId) . '&token=' . rawurlencode($oneTimeSecret);
            $flash = match ($connection['platform']) { 'hotmart' => 'Conexão Hotmart criada. O Hottok foi armazenado com segurança.', 'eduzz' => 'Conexão Eduzz criada. A chave foi armazenada com segurança.', 'applyfy' => 'Conexão Applyfy criada. A URL contém um token secreto; use o cabeçalho X-Affiliey-Webhook-Token se a plataforma permitir.', default => 'Conexão Kiwify criada. Copie o segredo agora; ele não será exibido novamente.' };
        } elseif (in_array($action, ['toggle', 'rotate'], true)) {
            $connectionId = (string)($_POST['id'] ?? '');
            if ($action === 'rotate') {
                $platformQuery = app_db()->prepare('SELECT platform FROM integration_connections WHERE id=? AND tenant_id=?');
                $platformQuery->execute([$connectionId, tenant_id()]);
                $oneTimePlatform = (string)$platformQuery->fetchColumn();
            }
            $oneTimeSecret = integration_change($connectionId, $action) ?? '';
            if ($action === 'rotate' && $oneTimePlatform === 'applyfy') $oneTimeWebhookUrl = $baseUrl . '?connection=' . rawurlencode($connectionId) . '&token=' . rawurlencode($oneTimeSecret);
            $flash = $action === 'rotate' ? 'Segredo renovado. Atualize o destino do webhook na plataforma.' : 'Status da conexão atualizado.';
        } elseif ($action === 'product_save') {
            integration_product_save((string)($_POST['connection_id'] ?? ''), (string)($_POST['external_product_id'] ?? ''), (string)($_POST['product_name'] ?? ''));
            $flash = 'Produto autorizado para esta conexão. Eventos de outros produtos serão ignorados.';
        } elseif ($action === 'product_toggle') {
            integration_product_toggle((string)($_POST['product_id'] ?? ''));
            $flash = 'Autorização do produto atualizada.';
        } elseif ($action === 'affiliate_link_save') {
            integration_affiliate_link_save((string)($_POST['connection_id'] ?? ''), (string)($_POST['affiliate_id'] ?? ''), (string)($_POST['external_affiliate_id'] ?? ''), (string)($_POST['external_email'] ?? ''));
            $flash = 'Vínculo externo do afiliado salvo para esta conexão.';
        } elseif ($action === 'affiliate_link_toggle') {
            integration_affiliate_link_toggle((string)($_POST['link_id'] ?? ''));
            $flash = 'Vínculo do afiliado atualizado.';
        } else $error = 'Ação inválida.';
    } catch (DomainException $e) { $error = $e->getMessage(); }
    catch (Throwable $e) { $error = 'Não foi possível atualizar a integração.'; }
}
$connections = integration_list();
$eligibleAffiliates = array_values(array_filter(affiliate_read_all(), static fn(array $affiliate): bool => ($affiliate['status'] ?? '') === 'active'));
$eventsStmt = app_db()->prepare('SELECT e.event_type,e.result,e.message,e.created_at,c.name AS connection_name,c.platform FROM integration_events e JOIN integration_connections c ON c.id=e.connection_id WHERE e.tenant_id=? ORDER BY e.created_at DESC LIMIT 30');
$eventsStmt->execute([tenant_id()]); $events = $eventsStmt->fetchAll();
function ine($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Integrações — AFFILIEY</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/integrations.css"><script src="assets/js/integrations.js" defer></script><link rel="stylesheet" href="assets/css/app-theme.css?v=3"><link rel="manifest" href="/manifest.webmanifest"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="apple-touch-icon" sizes="180x180" href="/brand/affiliey-apple-touch-icon.png"><link rel="stylesheet" href="/assets/css/pwa.css"><script src="/assets/js/pwa.js" defer></script><link rel="icon" type="image/png" href="/brand/affiliey-favicon.png"><link rel="stylesheet" href="/assets/css/brand.css?v=affiliey4"><link rel="stylesheet" href="/assets/css/workspace-premium.css?v=1"><link rel="stylesheet" href="/assets/css/sliding-pill-nav.css?v=2"><script src="/assets/js/sliding-pill-nav.js?v=1" defer></script><meta name="theme-color" content="#111827"><meta property="og:site_name" content="AFFILIEY"><meta name="description" content="Gestão de afiliados, vendas, metas e campanhas em uma plataforma."><meta property="og:description" content="Gestão de afiliados, vendas, metas e campanhas em uma plataforma."><meta property="og:type" content="website"><meta property="og:title" content="AFFILIEY | Plataforma de afiliados"><meta property="og:image" content="https://afiliados.horizoncafe.com.br/brand/affiliey-logo-light.png"><link rel="stylesheet" href="/assets/css/page-transitions.css?v=2"><script src="/assets/js/page-transitions.js?v=2" defer></script><link rel="stylesheet" href="/assets/css/integrations-premium.css?v=2"><link rel="stylesheet" href="/assets/css/typography.css?v=1"></head><body class="app-shell">
<header class="topbar"><a class="brand" href="dashboard.php"><picture class="brand-picture"><source media="(max-width: 640px)" srcset="/brand/affiliey-symbol.png"><img class="brand-logo" src="/brand/affiliey-logo-dark.png" alt="AFFILIEY"></picture></a><nav class="main-nav"><?= app_workspace_navigation() ?></nav><div class="top-actions"><?= app_header_account_tools() ?><span><?= ine(current_user()['name'] ?? '') ?></span><a href="login.php?logout=1">Sair</a></div></header>
<main class="page integrations-page"><div class="crumb"><a href="dashboard.php">Workspace</a> / Integrações</div><section class="welcome"><div><span class="eyebrow">DADOS DE VENDAS CONECTADOS</span><h1>Integrações</h1><p>Receba eventos da Kiwify, Hotmart, Eduzz e Applyfy e acompanhe as vendas em um só lugar.</p></div><div class="provider-set" aria-label="Plataformas disponíveis"><span><i>K</i>Kiwify</span><span><i>H</i>Hotmart</span><span><i>E</i>Eduzz</span><span><i>A</i>Applyfy</span></div></section><section class="integration-flow" aria-label="Fluxo de vendas integrado"><div class="flow-platforms"><span class="flow-kicker">FONTES DE VENDA</span><strong>Kiwify <i>K</i></strong><strong>Hotmart <i>H</i></strong><strong>Eduzz <i>E</i></strong><strong>Applyfy <i>A</i></strong></div><div class="flow-connector" aria-hidden="true"><span></span><span></span><span></span></div><div class="flow-center"><span class="flow-symbol">AF</span><span><b>AFFILIEY HUB</b><small>Eventos seguros em um só lugar</small></span></div><div class="flow-connector" aria-hidden="true"><span></span><span></span><span></span></div><div class="flow-output"><span class="flow-output-icon" aria-hidden="true">↗</span><span><b>VENDAS ATRIBUÍDAS</b><small>Dashboard · ranking · comissões</small></span></div></section><?php if ($flash): ?><div class="notice success"><?= ine($flash) ?></div><?php endif; ?><?php if ($error): ?><div class="notice error"><?= ine($error) ?></div><?php endif; ?>
<?php if ($oneTimeSecret !== ''): ?><section class="secret-box"><b><?= $oneTimePlatform === 'applyfy' ? 'URL autenticada Applyfy — copie agora' : 'Segredo Kiwify — copie agora' ?></b><p><?= $oneTimePlatform === 'applyfy' ? 'Cole a URL completa nos webhooks da Applyfy. Ela contém o token secreto; salve-a com segurança.' : 'Configure este segredo no webhook da Kiwify. Por segurança, não será exibido novamente.' ?></p><div class="copy-row"><input id="secretValue" readonly value="<?= ine($oneTimeWebhookUrl !== '' ? $oneTimeWebhookUrl : $oneTimeSecret) ?>"><button class="button primary" type="button" data-copy="secretValue"><?= $oneTimePlatform === 'applyfy' ? 'Copiar URL' : 'Copiar segredo' ?></button></div></section><?php endif; ?>
<div class="integration-grid"><section class="panel setup-panel"><div class="panel-heading"><div><h2>Conectar plataforma</h2><p>Importe vendas por webhooks autenticados.</p></div><span class="kiwify-icon">↗</span></div>
<form method="post" class="create-form"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="create"><label>Plataforma<select id="platformSelect" name="platform"><option value="kiwify">Kiwify</option><option value="hotmart">Hotmart</option><option value="eduzz">Eduzz</option><option value="applyfy">Applyfy</option></select></label><label>Nome para identificar a conta<input name="name" maxlength="80" placeholder="Ex.: Minha loja" required></label><label id="providerSecretField" hidden><span id="providerSecretLabel">Credencial</span><input id="providerSecretInput" name="hottok" type="password" maxlength="255" autocomplete="off" placeholder="Cole a credencial do webhook"><small id="providerSecretHelp">A credencial é criptografada e não volta a ser exibida.</small></label><button class="button primary" type="submit">＋ Criar conexão</button></form>
<div class="steps" data-platform-instructions="kiwify"><h3>Configurar a Kiwify</h3><ol><li>Crie a conexão; o AFFILIEY gera um segredo para assinar os eventos.</li><li>Na Kiwify, abra Apps → Webhooks, selecione os produtos e eventos de venda aprovada, reembolso e chargeback.</li><li>Cadastre o endereço do receptor e o segredo exibido após criar a conexão.</li></ol><div class="endpoint-preview"><small>Formato do endereço</small><code><?= ine($baseUrl) ?>?connection=ID_DA_CONEXAO&amp;signature=ASSINATURA_KIWIFY</code></div></div>
<div class="steps" data-platform-instructions="hotmart" hidden><h3>Configurar a Hotmart</h3><ol><li>Na Hotmart, abra Ferramentas → Webhook e crie uma configuração na versão 2.0.0.</li><li>Use o endereço específico da conexão, mostrado na lista ao lado, e selecione eventos de compra aprovada, reembolso, chargeback e cancelamento.</li><li>Copie o Hottok da configuração da Hotmart e cole no formulário acima antes de criar a conexão.</li><li>No cadastro do afiliado, informe o código <code>affiliate_code</code> da Hotmart para atribuir as vendas automaticamente.</li></ol><p>O AFFILIEY valida o cabeçalho <code>X-HOTMART-HOTTOK</code> antes de registrar pedidos.</p></div>
<div class="steps" data-platform-instructions="eduzz" hidden><h3>Configurar a Eduzz</h3><ol><li>No Console do Desenvolvedor da Eduzz, configure o webhook e informe aqui o originSecret que a Eduzz envia no campo data.producer.originSecret.</li><li>Crie o webhook para o endereço desta conexão e selecione os eventos de fatura paga, aguardando pagamento, reembolsada, chargeback e cancelada.</li><li>Vincule o ID do afiliado da Eduzz ao cadastro correspondente abaixo; o e-mail sozinho não libera acesso nem importa vendas.</li></ol><p>O AFFILIEY valida o originSecret recebido no corpo antes de processar o evento.</p></div>
<div class="steps" data-platform-instructions="applyfy" hidden><h3>Configurar a Applyfy</h3><ol><li>Crie a conexão para gerar uma URL de webhook exclusiva com token secreto.</li><li>Na Applyfy, acesse Integrações → Webhooks, crie um webhook para cada produto autorizado e selecione eventos de compra aprovada, pendente, cancelada e reembolsada.</li><li>Prefira enviar o token no cabeçalho <code>X-Affiliey-Webhook-Token</code>, se disponível. A URL autenticada continua disponível para compatibilidade; trate-a como senha e evite compartilhá-la ou mantê-la em logs.</li><li>Cadastre o ID oficial do produto e vincule o ID/código do afiliado da Applyfy nos campos abaixo. Eventos sem correspondência são ignorados.</li></ol><p>A documentação consultada da Applyfy não informa se webhooks permitem cabeçalhos personalizados; confirme essa opção com o suporte da plataforma. Veja também a documentação oficial de <a href="https://ajuda.applyfy.com.br/pt-br/article/como-funcionam-os-webhooks-1sz3qe0/" target="_blank" rel="noopener">webhooks</a> e da <a href="https://ajuda.applyfy.com.br/pt-br/article/como-funciona-a-api-da-applyfy-fmud40/" target="_blank" rel="noopener">API pública</a>. Este conector usa webhooks; a descoberta de produtos pela API ainda não está habilitada. A documentação pública não detalha o formato do payload de vendas: faça um envio de teste e confira o resultado em “Eventos recebidos”; campos que não forem reconhecidos serão rejeitados ou ignorados.</p></div>
<?php if (!$https): ?><div class="warning">Este endereço está em HTTP. Para receber webhooks externos, publique o sistema em um domínio com HTTPS.</div><?php endif; ?></section>
<section class="panel connection-panel"><div class="panel-heading"><div><h2>Suas conexões</h2><p><?= count($connections) ?> conexão(ões) neste espaço</p></div></div><?php if (!$connections): ?><div class="empty-state"><span>↗</span><b>Nenhuma conexão ainda</b><small>Crie uma conexão Kiwify, Hotmart ou Eduzz para começar.</small></div><?php endif; ?>
<?php foreach ($connections as $connection):
    $platform = (string)$connection['platform'];
    $platformLabel = ['kiwify'=>'Kiwify','hotmart'=>'Hotmart','eduzz'=>'Eduzz','applyfy'=>'Applyfy'][$platform] ?? ucfirst($platform);
    $platformMark = ['kiwify'=>'K','hotmart'=>'H','eduzz'=>'E','applyfy'=>'A'][$platform] ?? '?';
    $endpoint = $baseUrl . '?connection=' . rawurlencode($connection['id']) . ($platform === 'kiwify' ? '&signature=ASSINATURA_KIWIFY' : ($platform === 'applyfy' ? '&token=TOKEN_SECRETO' : ''));
    $products = integration_product_list((string)$connection['id']);
    $affiliateLinks = integration_affiliate_link_list((string)$connection['id']);
?>
<article class="connection">
  <div class="connection-title"><span class="kiwify-icon"><?= ine($platformMark) ?></span><span><b><?= ine($connection['name']) ?></b><small><?= ine($platformLabel) ?> · <?= $connection['status'] === 'active' ? 'Recebendo eventos' : 'Pausada' ?></small></span><span class="state <?= ine($connection['status']) ?>"><?= $connection['status'] === 'active' ? 'Ativa' : 'Pausada' ?></span></div>
  <div class="connection-stats"><span><b><?= (int)$connection['event_count'] ?></b> eventos</span><span><b><?= (int)$connection['order_count'] ?></b> vendas vinculadas</span><span><b><?= count(array_filter($products, static fn(array $p): bool => $p['status'] === 'active')) ?></b> produtos ativos</span></div>
  <section class="connection-scope">
    <div class="scope-heading"><h3>Produtos autorizados</h3><small>Somente estes IDs podem gerar vendas neste espaço. Nesta etapa, informe o ID oficial do produto exibido pela plataforma; descoberta automática via API/OAuth depende da configuração dos aplicativos oficiais AFFILIEY.</small></div>
    <form method="post" class="scope-form product-form"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="product_save"><input type="hidden" name="connection_id" value="<?= ine($connection['id']) ?>"><label>ID oficial do produto<input name="external_product_id" maxlength="120" required placeholder="ID informado pela plataforma"></label><label>Nome do produto<input name="product_name" maxlength="160" required placeholder="Nome para identificar"></label><button class="button primary" type="submit">Autorizar produto</button></form>
    <?php if ($products): ?><ul class="scope-list"><?php foreach ($products as $product): ?><li><span><b><?= ine($product['name']) ?></b><small>ID <?= ine($product['external_product_id']) ?> · <?= $product['status'] === 'active' ? 'Sincronizando' : 'Pausado' ?></small></span><form method="post"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="product_toggle"><input type="hidden" name="product_id" value="<?= ine($product['id']) ?>"><button class="text-button" type="submit"><?= $product['status'] === 'active' ? 'Desautorizar' : 'Reativar' ?></button></form></li><?php endforeach; ?></ul><?php else: ?><p class="scope-empty">Cadastre pelo menos um produto autorizado para começar a receber vendas.</p><?php endif; ?>
  </section>
  <section class="connection-scope affiliate-scope">
    <div class="scope-heading"><h3>Vínculos de afiliados</h3><small>Associe explicitamente o ID externo a um afiliado ativo. O e-mail opcional só é considerado dentro deste vínculo manual.</small></div>
    <?php if ($eligibleAffiliates): ?><form method="post" class="scope-form affiliate-form"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="affiliate_link_save"><input type="hidden" name="connection_id" value="<?= ine($connection['id']) ?>"><label>Afiliado AFFILIEY<select name="affiliate_id" required><?php foreach ($eligibleAffiliates as $affiliate): ?><option value="<?= ine($affiliate['id']) ?>"><?= ine($affiliate['name']) ?> · <?= ine($affiliate['email']) ?></option><?php endforeach; ?></select></label><label>ID/código externo<input name="external_affiliate_id" maxlength="120" required placeholder="ID ou código na plataforma"></label><label>E-mail externo (opcional)<input type="email" name="external_email" maxlength="190" placeholder="E-mail da conta externa"></label><button class="button" type="submit">Salvar vínculo</button></form><?php else: ?><p class="scope-empty">Cadastre e ative um afiliado antes de criar vínculos externos.</p><?php endif; ?>
    <?php if ($affiliateLinks): ?><ul class="scope-list"><?php foreach ($affiliateLinks as $link): ?><li><span><b><?= ine($link['affiliate_name']) ?></b><small><?= ine($link['external_affiliate_id']) ?><?= $link['external_email'] !== '' ? ' · '.ine($link['external_email']) : '' ?> · <?= $link['status'] === 'active' ? 'Ativo' : 'Pausado' ?></small></span><form method="post"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="affiliate_link_toggle"><input type="hidden" name="link_id" value="<?= ine($link['id']) ?>"><button class="text-button" type="submit"><?= $link['status'] === 'active' ? 'Desativar' : 'Ativar' ?></button></form></li><?php endforeach; ?></ul><?php endif; ?>
  </section>
  <div class="endpoint-line"><?php if ($platform === 'applyfy'): ?><span>URL autenticada não é exibida novamente. Se precisar recuperar, renove o segredo e copie a nova URL gerada.</span><?php else: ?><input readonly value="<?= ine($endpoint) ?>"><button type="button" class="button" data-copy-input>Copiar URL</button><?php endif; ?></div>
  <div class="connection-actions"><form method="post"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= ine($connection['id']) ?>"><button class="text-button" type="submit"><?= $connection['status'] === 'active' ? 'Pausar conexão' : 'Reativar conexão' ?></button></form><?php if (in_array($platform,['kiwify','applyfy'],true)): ?><form method="post" onsubmit="return confirm('O token antigo deixará de funcionar. Atualize o webhook na plataforma. Continuar?')"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="rotate"><input type="hidden" name="id" value="<?= ine($connection['id']) ?>"><button class="text-button" type="submit">Renovar segredo</button></form><?php endif; ?></div>
</article><?php endforeach; ?></section></div>
<section class="panel log-panel"><div class="panel-heading"><div><h2>Eventos recebidos</h2><p>Últimos 30 eventos, incluindo recusas por produto ou afiliado não autorizado. Payloads brutos não são armazenados.</p></div></div><div class="table-scroll"><table><thead><tr><th>Horário</th><th>Plataforma / conexão</th><th>Evento</th><th>Resultado</th><th>Detalhe</th></tr></thead><tbody><?php if (!$events): ?><tr><td colspan="5" class="empty">Ainda não recebemos eventos.</td></tr><?php endif; ?><?php foreach ($events as $event): ?><tr><td><?= ine(date('d/m/Y H:i', strtotime($event['created_at']))) ?></td><td><?= ine(ucfirst($event['platform']) . ' · ' . $event['connection_name']) ?></td><td><code><?= ine($event['event_type']) ?></code></td><td><span class="result <?= ine($event['result']) ?>"><?= ine($event['result']) ?></span></td><td><?= ine($event['message'] ?: 'Processado') ?></td></tr><?php endforeach; ?></tbody></table></div></section><p class="footnote">As vendas só entram se o produto estiver autorizado e o afiliado corresponder a um vínculo externo ativo ou a um identificador exato do afiliado deste espaço.</p></main></body></html>
