<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';require_once __DIR__ . '/../modules/integrations.php';require_login();require_role(['owner','admin']);start_app_session();
if(empty($_SESSION['integrations_csrf']))$_SESSION['integrations_csrf']=bin2hex(random_bytes(32));$csrf=$_SESSION['integrations_csrf'];$error='';$flash='';$oneTimeSecret='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Sessão expirada. Atualize a página.');}
    try{$action=(string)($_POST['action']??'');if($action==='create'){$connection=integration_create((string)($_POST['name']??''));$oneTimeSecret=$connection['token'];$createdId=$connection['id'];$flash='Conexão criada. Copie o segredo agora; ele não será exibido novamente.';}elseif(in_array($action,['toggle','rotate'],true)){$oneTimeSecret=integration_change((string)($_POST['id']??''),$action)??'';$flash=$action==='rotate'?'Segredo renovado. Atualize também o webhook na Kiwify.':'Status da conexão atualizado.';}else $error='Ação inválida.';}catch(DomainException $e){$error=$e->getMessage();}catch(Throwable $e){$error='Não foi possível atualizar a integração.';}
}
$connections=integration_list();$eventsStmt=app_db()->prepare('SELECT e.event_type,e.result,e.message,e.created_at,c.name AS connection_name FROM integration_events e JOIN integration_connections c ON c.id=e.connection_id WHERE e.tenant_id=? ORDER BY e.created_at DESC LIMIT 30');$eventsStmt->execute([tenant_id()]);$events=$eventsStmt->fetchAll();
$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';$origin=($https?'https://':'http://').($_SERVER['HTTP_HOST']??'localhost');$baseUrl=$origin.'/webhook.php';
function ine($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Integrações — Vértice</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/integrations.css"><script src="assets/js/integrations.js" defer></script><link rel="stylesheet" href="assets/css/app-theme.css?v=2"></head><body class="app-shell"><header class="topbar"><a class="brand" href="dashboard.php"><span class="brand-mark">v</span> vértice<span class="brand-dot">.</span></a><nav class="main-nav"><a href="dashboard.php">Visão geral</a><a href="affiliates.php">Afiliados</a><a href="sales.php">Vendas</a><a href="campaigns.php">Metas</a><?php if(in_array(current_user()['role']??'', ['owner','admin'],true)): ?><a href="team.php">Equipe</a><a class="selected" href="integrations.php">Integrações</a><?php endif; ?></nav><div class="top-actions"><span><?= ine(current_user()['name']??'') ?></span><a href="login.php?logout=1">Sair</a></div></header><main class="page"><div class="crumb"><a href="dashboard.php">Workspace</a> / Integrações</div><section class="welcome"><div><span class="eyebrow">DADOS DE VENDAS CONECTADOS</span><h1>Integrações</h1><p>Receba eventos de venda da Kiwify e acompanhe o resultado junto aos afiliados.</p></div><span class="kiwify-badge">K Kiwify</span></section>
<?php if($flash): ?><div class="notice success"><?= ine($flash) ?></div><?php endif; ?><?php if($error): ?><div class="notice error"><?= ine($error) ?></div><?php endif; ?>
<?php if($oneTimeSecret): ?><section class="secret-box"><b>Segredo de webhook — copie agora</b><p>Configure este segredo na Kiwify para assinar os eventos desta conexão. Por segurança, guardamos o segredo criptografado e não o mostramos novamente.</p><div class="copy-row"><input id="secretValue" readonly value="<?= ine($oneTimeSecret) ?>"><button class="button primary" type="button" data-copy="secretValue">Copiar segredo</button></div></section><?php endif; ?>
<div class="integration-grid"><section class="panel setup-panel"><div class="panel-heading"><div><h2>Conectar Kiwify</h2><p>Conexão por webhook, sem importar dados pessoais de compradores.</p></div><span class="kiwify-icon">K</span></div><form method="post" class="create-form"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="create"><label>Nome para identificar esta conta<input name="name" maxlength="80" placeholder="Ex.: Minha loja Kiwify" required></label><button class="button primary" type="submit">＋ Criar conexão</button></form><div class="steps"><h3>Como ativar</h3><ol><li>Crie uma conexão para gerar o endereço e o segredo de assinatura.</li><li>Na Kiwify, abra <b>Apps → Webhooks</b>, escolha os produtos e os eventos de venda aprovada, reembolso e chargeback.</li><li>Cadastre o endereço abaixo e configure o segredo gerado como token do webhook. A Kiwify assina o JSON enviado; o Vértice valida essa assinatura antes de registrar os dados.</li><li>Envie um evento de teste e confira o resultado nos logs.</li></ol><div class="endpoint-preview"><small>Endereço do receptor</small><code><?= ine($baseUrl) ?>?connection=ID_DA_CONEXAO&amp;signature=ASSINATURA_KIWIFY</code></div><?php if(!$https): ?><div class="warning">Este endereço local usa HTTP e não é acessível pela Kiwify. Para receber vendas reais, publique o app em uma hospedagem com HTTPS.</div><?php endif; ?></div></section>
<section class="panel connection-panel"><div class="panel-heading"><div><h2>Suas conexões</h2><p><?= count($connections) ?> conexão(ões) neste espaço</p></div></div><?php if(!$connections): ?><div class="empty-state"><span>↗</span><b>Nenhuma conexão ainda</b><small>Crie uma conexão Kiwify para começar a receber eventos.</small></div><?php endif; ?><?php foreach($connections as $connection): $endpoint=$baseUrl.'?connection='.rawurlencode($connection['id']).'&signature=ASSINATURA_KIWIFY'; ?><article class="connection"><div class="connection-title"><span class="kiwify-icon">K</span><span><b><?= ine($connection['name']) ?></b><small><?= $connection['status']==='active'?'Recebendo eventos':'Pausada' ?></small></span><span class="state <?= ine($connection['status']) ?>"><?= $connection['status']==='active'?'Ativa':'Pausada' ?></span></div><div class="connection-stats"><span><b><?= (int)$connection['event_count'] ?></b> eventos</span><span><b><?= (int)$connection['order_count'] ?></b> pedidos</span><span>Último evento: <b><?= $connection['last_event_at']?ine(date('d/m/Y H:i',strtotime($connection['last_event_at']))):'—' ?></b></span></div><div class="endpoint-line"><input readonly value="<?= ine($endpoint) ?>"><button type="button" class="button" data-copy-input>Copiar URL</button></div><div class="connection-actions"><form method="post"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= ine($connection['id']) ?>"><button class="text-button" type="submit"><?= $connection['status']==='active'?'Pausar':'Reativar' ?></button></form><form method="post" onsubmit="return confirm('O segredo antigo deixará de funcionar. Você precisará atualizar o webhook na Kiwify. Continuar?')"><input type="hidden" name="csrf" value="<?= ine($csrf) ?>"><input type="hidden" name="action" value="rotate"><input type="hidden" name="id" value="<?= ine($connection['id']) ?>"><button class="text-button" type="submit">Renovar segredo</button></form></div></article><?php endforeach; ?></section></div>
<section class="panel log-panel"><div class="panel-heading"><div><h2>Eventos recebidos</h2><p>Últimos 30 eventos. Dados pessoais e payloads brutos não são armazenados.</p></div></div><div class="table-scroll"><table><thead><tr><th>Horário</th><th>Conexão</th><th>Evento Kiwify</th><th>Resultado</th><th>Detalhe</th></tr></thead><tbody><?php if(!$events): ?><tr><td colspan="5" class="empty">Ainda não recebemos eventos.</td></tr><?php endif; ?><?php foreach($events as $event): ?><tr><td><?= ine(date('d/m/Y H:i',strtotime($event['created_at']))) ?></td><td><?= ine($event['connection_name']) ?></td><td><code><?= ine($event['event_type']) ?></code></td><td><span class="result <?= ine($event['result']) ?>"><?= ine($event['result']) ?></span></td><td><?= ine($event['message']?:'Processado') ?></td></tr><?php endforeach; ?></tbody></table></div></section><p class="footnote">O webhook atualiza vendas e pedidos dos afiliados identificados pelo e-mail de afiliado informado pela Kiwify. Os demais pedidos aparecem sem atribuição.</p></main></body></html>
