<?php
declare(strict_types=1);
require_once __DIR__.'/../modules/auth.php';require_once __DIR__.'/../modules/affiliate-community.php';require_once __DIR__.'/../modules/affiliate-groups.php';require_once __DIR__.'/../modules/affiliates.php';
require_login();start_app_session();if(empty($_SESSION['material_csrf']))$_SESSION['material_csrf']=bin2hex(random_bytes(32));$csrf=(string)$_SESSION['material_csrf'];$error='';$flash='';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($csrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Sessão expirada. Atualize a página.');}try{$action=(string)($_POST['action']??'save');if($action==='toggle'){if(!app_user_can('materials','edit'))throw new DomainException('Sem permissão para arquivar materiais.');affiliate_material_toggle((string)($_POST['id']??''),(string)current_user()['id']);$flash='Status do material atualizado.';}else{if(!app_user_can('materials',trim((string)($_POST['id']??''))===''?'create':'edit'))throw new DomainException('Sem permissão para esta ação.');affiliate_material_save($_POST,(string)current_user()['id']);$flash='Material salvo e disponibilizado ao público selecionado.';}}catch(DomainException $e){$error=$e->getMessage();}catch(Throwable $e){$error='Não foi possível salvar o material.';error_log('[AFFILIEY] materials: '.$e->getMessage());}}
$materials=affiliate_material_list();$affiliates=affiliate_read_all();$groups=affiliate_group_list();function mt_e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Materiais — AFFILIEY</title><link rel="stylesheet" href="/assets/css/app-theme.css?v=3"><link rel="stylesheet" href="/assets/css/brand.css?v=affiliey4"><link rel="stylesheet" href="/assets/css/profile-environments.css?v=1"><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/brand/affiliey-favicon.png"></head><body class="app-shell"><header class="topbar"><a class="brand" href="dashboard.php"><img class="brand-logo" src="/brand/affiliey-logo-dark.png" alt="AFFILIEY"></a><nav class="main-nav"><?= app_workspace_navigation() ?></nav><div class="top-actions"><span><?= mt_e(current_user()['name']??'') ?></span><a href="login.php?logout=1">Sair</a></div></header><main class="profile-page"><div class="profile-heading"><div><span class="profile-eyebrow">RECURSOS DA EQUIPE</span><h1>Materiais de divulgação</h1><p>Compartilhe links HTTPS com toda a rede, um grupo ou um afiliado.</p></div></div><?php if($error): ?><p class="message error" role="alert"><?= mt_e($error) ?></p><?php endif; ?><?php if($flash): ?><p class="message success" role="status"><?= mt_e($flash) ?></p><?php endif; ?>
<?php if(app_user_can('materials','create')||app_user_can('materials','edit')): ?><section class="profile-panel"><div class="profile-panel-head"><div><h2>Publicar material</h2><p>Informe um link externo seguro (HTTPS). O AFFILIEY não hospeda arquivos nesta tela.</p></div></div><form method="post" class="community-form"><input type="hidden" name="csrf" value="<?= mt_e($csrf) ?>"><input type="hidden" name="action" value="save"><label>Título<input name="title" maxlength="160" required></label><label>Link HTTPS<input name="url" type="url" placeholder="https://..." maxlength="2000" required></label><label>Descrição<textarea name="description" maxlength="4000" rows="3"></textarea></label><label>Público<select name="audience_type"><option value="all">Toda a rede</option><option value="group">Um grupo</option><option value="affiliate">Um afiliado</option></select></label><label>Grupo<select name="group"><option value="">Selecione</option><?php foreach($groups as $g): ?><option value="<?= mt_e($g['name']) ?>"><?= mt_e($g['name']) ?></option><?php endforeach; ?></select></label><label>Afiliado<select name="affiliate_id"><option value="">Selecione</option><?php foreach($affiliates as $a): if($a['status']!=='active')continue; ?><option value="<?= mt_e($a['id']) ?>"><?= mt_e($a['name']) ?></option><?php endforeach; ?></select></label><button class="button primary" type="submit">Publicar material</button></form></section><?php endif; ?>
<section class="profile-panel"><div class="profile-panel-head"><div><h2>Materiais publicados</h2><p>O público e o estado são verificados no servidor.</p></div></div><?php if(!$materials): ?><p class="profile-muted">Nenhum material publicado.</p><?php else: ?><div class="profile-resource-list"><?php foreach($materials as $m): ?><article><div><span class="profile-product-platform"><?= mt_e(['all'=>'Toda a rede','group'=>'Grupo · '.$m['audience_group'],'affiliate'=>'Afiliado'][$m['audience_type']]??$m['audience_type']) ?> · <?= $m['active']?'Ativo':'Arquivado' ?></span><h3><?= mt_e($m['title']) ?></h3><p><?= nl2br(mt_e($m['description'])) ?></p><a href="<?= mt_e($m['resource_url']) ?>" target="_blank" rel="noopener noreferrer">Abrir recurso ↗</a></div><?php if(app_user_can('materials','edit')): ?><form method="post"><input type="hidden" name="csrf" value="<?= mt_e($csrf) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= mt_e($m['id']) ?>"><button class="button" type="submit"><?= $m['active']?'Arquivar':'Reativar' ?></button></form><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?></section></main></body></html>
