<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';
require_once __DIR__ . '/../modules/affiliates.php';
require_once __DIR__ . '/../modules/integrations.php';
require_login();
$affiliates = affiliate_read_all();
$salesTotal = array_sum(array_column($affiliates, 'sales'));
$ordersTotal = array_sum(array_column($affiliates, 'orders'));
$commissionTotal = array_sum(array_map(static fn($a) => (float)$a['sales'] * (float)$a['commission'] / 100, $affiliates));
$orderStmt=app_db()->prepare('SELECT o.external_order_id,o.affiliate_code,o.amount_cents,o.status,o.sold_at,c.name AS connection_name,a.name AS affiliate_name FROM sales_orders o JOIN integration_connections c ON c.id=o.connection_id LEFT JOIN affiliates a ON a.id=o.affiliate_id AND a.tenant_id=o.tenant_id WHERE o.tenant_id=? ORDER BY o.sold_at DESC LIMIT 50');$orderStmt->execute([tenant_id()]);$integratedOrders=$orderStmt->fetchAll();
$kiwifySummary=app_db()->prepare("SELECT COUNT(*) AS orders,COALESCE(SUM(CASE WHEN status='approved' THEN amount_cents ELSE 0 END),0) AS approved_cents,COALESCE(SUM(CASE WHEN status='refunded' THEN amount_cents ELSE 0 END),0) AS refunded_cents FROM sales_orders WHERE tenant_id=?");$kiwifySummary->execute([tenant_id()]);$kiwifyStats=$kiwifySummary->fetch();
$search = trim((string)($_GET['q'] ?? ''));
$groupFilter = (string)($_GET['group'] ?? 'all');
$statusFilter = (string)($_GET['status'] ?? 'all');
$groups = array_values(array_unique(array_map(static fn($a) => (string)$a['group'], $affiliates)));
$rows = array_values(array_filter($affiliates, static function($a) use($search,$groupFilter,$statusFilter){
    $matches = $search === '' || stripos($a['name'].' '.$a['email'].' '.$a['code'], $search) !== false;
    return $matches && ($groupFilter === 'all' || $a['group'] === $groupFilter) && ($statusFilter === 'all' || $a['status'] === $statusFilter);
}));
usort($rows, static fn($a,$b) => (float)$b['sales'] <=> (float)$a['sales']);
$money = static fn($v) => 'R$ '.number_format((float)$v,2,',','.');
function se($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vendas — Vértice</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/sales.css"><link rel="stylesheet" href="assets/css/sales-integrations.css"><script src="assets/js/sales.js" defer></script><link rel="stylesheet" href="assets/css/app-theme.css?v=2"></head><body class="app-shell">
<header class="topbar"><a class="brand" href="dashboard.php"><span class="brand-mark">v</span> vértice<span class="brand-dot">.</span></a><nav class="main-nav"><a href="dashboard.php">Visão geral</a><a href="affiliates.php">Afiliados</a><a class="selected" href="sales.php">Vendas</a><a href="campaigns.php">Metas</a><a href="announcements.php">Comunicados</a><?php if(in_array(current_user()['role']??'', ['owner','admin'], true)): ?><a href="team.php">Equipe</a><a href="integrations.php">Integrações</a><?php endif; ?></nav><div class="top-actions"><span class="hello"><?= se(current_user()['name'] ?? '') ?></span><a class="logout" href="login.php?logout=1">Sair</a></div></header>
<main class="page"><div class="crumb"><a href="dashboard.php">Workspace</a> / Vendas</div><section class="welcome"><div><span class="eyebrow">DESEMPENHO COMERCIAL</span><h1>Vendas da equipe</h1><p>Acompanhe o faturamento e as comissões atribuídas a cada afiliado.</p></div><button class="button primary" id="exportBtn">↓ Exportar CSV</button></section>
<section class="stats"><article class="stat-card"><span>Faturamento atribuído</span><strong><?= $money($salesTotal) ?></strong><small>Somatório das vendas da equipe</small></article><article class="stat-card"><span>Pedidos registrados</span><strong><?= number_format((int)$ordersTotal,0,',','.') ?></strong><small>Quantidade informada por afiliado</small></article><article class="stat-card"><span>Comissões estimadas</span><strong><?= $money($commissionTotal) ?></strong><small>Calculadas pela comissão de cada afiliado</small></article><article class="stat-card"><span>Afiliados com vendas</span><strong><?= count(array_filter($affiliates,static fn($a)=>(float)$a['sales']>0)) ?></strong><small>Com faturamento acima de zero</small></article><article class="stat-card"><span>Vendas recebidas da Kiwify</span><strong><?= $money(((int)$kiwifyStats['approved_cents'])/100) ?></strong><small><?= (int)$kiwifyStats['orders'] ?> pedidos registrados · estornos: <?= $money(((int)$kiwifyStats['refunded_cents'])/100) ?></small></article></section>
<section class="panel"><form class="filters" method="get"><label class="search">⌕ <input name="q" value="<?= se($search) ?>" placeholder="Buscar afiliado, e-mail ou código"></label><select name="group" aria-label="Filtrar por grupo"><option value="all">Todos os grupos</option><?php foreach($groups as $group): ?><option value="<?= se($group) ?>" <?= $groupFilter===$group?'selected':'' ?>><?= se($group) ?></option><?php endforeach; ?></select><select name="status" aria-label="Filtrar por status"><option value="all">Todos os status</option><option value="active" <?= $statusFilter==='active'?'selected':'' ?>>Ativos</option><option value="pending" <?= $statusFilter==='pending'?'selected':'' ?>>Pendentes</option><option value="inactive" <?= $statusFilter==='inactive'?'selected':'' ?>>Inativos</option></select><button class="button" type="submit">Aplicar filtros</button></form>
<div class="table-scroll"><table id="salesTable"><thead><tr><th>Afiliado</th><th>Grupo</th><th>Pedidos</th><th>Faturamento</th><th>Comissão</th><th>Comissão estimada</th><th>Status</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="7" class="empty">Nenhum resultado encontrado.</td></tr><?php endif; ?>
<?php foreach($rows as $a): $commission=(float)$a['sales']*(float)$a['commission']/100; $initials=affiliate_initials((string)$a['name']); $status=['active'=>'Ativo','pending'=>'Pendente','inactive'=>'Inativo'][$a['status']]??'Ativo'; ?><tr><td><span class="person"><i class="avatar"><?= se($initials) ?></i><span><b><?= se($a['name']) ?></b><small><?= se($a['email']) ?></small></span></span></td><td><?= se($a['group']) ?></td><td><?= number_format((int)$a['orders'],0,',','.') ?></td><td class="money"><?= $money($a['sales']) ?></td><td><?= se($a['commission']) ?>%</td><td class="money"><?= $money($commission) ?></td><td><span class="status <?= se($a['status']) ?>"><?= se($status) ?></span></td></tr><?php endforeach; ?>
</tbody></table></div></section>
<section class="panel order-panel"><div class="panel-heading"><div><h2>Pedidos recebidos por integração</h2><p>Até 50 pedidos mais recentes, sem armazenar dados pessoais do comprador.</p></div><a href="integrations.php">Ver integrações →</a></div><div class="table-scroll"><table><thead><tr><th>Pedido</th><th>Data</th><th>Afiliado</th><th>Origem</th><th>Valor</th><th>Status</th></tr></thead><tbody><?php if(!$integratedOrders): ?><tr><td colspan="6" class="empty">Nenhum pedido integrado ainda. <a href="integrations.php">Configure a Kiwify</a>.</td></tr><?php endif; ?><?php foreach($integratedOrders as $order): ?><tr><td><code><?= se($order['external_order_id']) ?></code></td><td><?= se(date('d/m/Y H:i',strtotime($order['sold_at']))) ?></td><td><?= se($order['affiliate_name']?:'Sem atribuição') ?></td><td><?= se($order['connection_name']) ?></td><td class="money"><?= $money($order['amount_cents']/100) ?></td><td><span class="status <?= $order['status']==='approved'?'active':'inactive' ?>"><?= ['approved'=>'Aprovada','refunded'=>'Reembolsada','canceled'=>'Cancelada'][$order['status']] ?></span></td></tr><?php endforeach; ?></tbody></table></div></section><p class="note">Resumo por afiliado e pedidos integrados. Consulte Integrações para ver a atividade dos webhooks.</p></main></body></html>
