<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';
require_once __DIR__ . '/../modules/affiliates.php';
require_once __DIR__ . '/../modules/integrations.php';
require_login();
$affiliates = affiliate_read_all();
$salesTotal = array_sum(array_column($affiliates, 'sales'));
$ordersTotal = array_sum(array_column($affiliates, 'orders'));
$commissionTotal = array_sum(array_map(static fn($a) => (float)$a['sales'] * (float)$a['commission'] / 100, $affiliates));
$orderStmt=app_db()->prepare('SELECT o.external_order_id,o.external_product_id,o.product_name,o.affiliate_code,o.amount_cents,o.commission_cents,o.status,o.sold_at,c.name AS connection_name,a.name AS affiliate_name FROM sales_orders o JOIN integration_connections c ON c.id=o.connection_id LEFT JOIN affiliates a ON a.id=o.affiliate_id AND a.tenant_id=o.tenant_id WHERE o.tenant_id=? ORDER BY o.sold_at DESC LIMIT 50');$orderStmt->execute([tenant_id()]);$integratedOrders=$orderStmt->fetchAll();
$kiwifySummary=app_db()->prepare("SELECT COUNT(*) AS orders,COALESCE(SUM(CASE WHEN status='approved' THEN amount_cents ELSE 0 END),0) AS approved_cents,COALESCE(SUM(CASE WHEN status='refunded' THEN amount_cents ELSE 0 END),0) AS refunded_cents FROM sales_orders WHERE tenant_id=?");$kiwifySummary->execute([tenant_id()]);$kiwifyStats=$kiwifySummary->fetch();
$search = trim((string)($_GET['q'] ?? ''));
$groupFilter = (string)($_GET['group'] ?? 'all');
$statusFilter = (string)($_GET['status'] ?? 'all');
$groups = array_values(array_unique(array_map(static fn($a) => (string)$a['group'], $affiliates)));
$rows = array_values(array_filter($affiliates, static function($a) use($search,$groupFilter,$statusFilter){
    $matches = $search === '' || stripos($a['name'].' '.$a['email'].' '.$a['code'], $search) !== false;
    return $matches && ($groupFilter === 'all' || $a['group'] === $groupFilter) && ($statusFilter === 'all' || $a['status'] === $statusFilter);
}));
usort($rows, static fn($a,$b) => (float)$b['sales'] <=> (float)$a['sales']);
$money = static fn($v) => 'R$ '.number_format((float)$v,2,',','.');
function se($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vendas — AFFILIEY</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/sales.css"><link rel="stylesheet" href="assets/css/sales-integrations.css"><script src="assets/js/sales.js" defer></script><link rel="stylesheet" href="assets/css/app-theme.css?v=3"><link rel="manifest" href="/manifest.webmanifest"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="apple-touch-icon" sizes="180x180" href="/brand/affiliey-apple-touch-icon.png"><link rel="stylesheet" href="/assets/css/pwa.css"><script src="/assets/js/pwa.js" defer></script><link rel="icon" type="image/png" href="/brand/affiliey-favicon.png"><link rel="stylesheet" href="/assets/css/brand.css?v=affiliey4"><link rel="stylesheet" href="/assets/css/workspace-premium.css?v=1"><link rel="stylesheet" href="/assets/css/sliding-pill-nav.css?v=2"><script src="/assets/js/sliding-pill-nav.js?v=1" defer></script><meta name="theme-color" content="#111827"><meta property="og:site_name" content="AFFILIEY"><meta name="description" content="Gestão de afiliados, vendas, metas e campanhas em uma plataforma."><meta property="og:description" content="Gestão de afiliados, vendas, metas e campanhas em uma plataforma."><meta property="og:type" content="website"><meta property="og:title" content="AFFILIEY | Plataforma de afiliados"><meta property="og:image" content="https://afiliados.horizoncafe.com.br/brand/affiliey-logo-light.png"><link rel="stylesheet" href="/assets/css/page-transitions.css?v=2"><script src="/assets/js/page-transitions.js?v=2" defer></script><link rel="stylesheet" href="/assets/css/typography.css?v=1"></head><body class="app-shell">
<header class="topbar"><a class="brand" href="dashboard.php"><picture class="brand-picture"><source media="(max-width: 640px)" srcset="/brand/affiliey-symbol.png"><img class="brand-logo" src="/brand/affiliey-logo-dark.png" alt="AFFILIEY"></picture></a><nav class="main-nav"><?= app_workspace_navigation() ?></nav><div class="top-actions"><?= app_header_account_tools() ?><span class="hello"><?= se(current_user()['name'] ?? '') ?></span><a class="logout" href="login.php?logout=1">Sair</a></div></header>
<main class="page"><div class="crumb"><a href="dashboard.php">Workspace</a> / Vendas</div><section class="welcome"><div><span class="eyebrow">DESEMPENHO COMERCIAL</span><h1>Vendas da equipe</h1><p>Acompanhe o faturamento e as comissões atribuídas a cada afiliado.</p></div><button class="button primary" id="exportBtn">↓ Exportar CSV</button></section>
<section class="stats"><article class="stat-card"><span>Faturamento atribuído</span><strong><?= $money($salesTotal) ?></strong><small>Somatório das vendas da equipe</small></article><article class="stat-card"><span>Pedidos registrados</span><strong><?= number_format((int)$ordersTotal,0,',','.') ?></strong><small>Quantidade informada por afiliado</small></article><article class="stat-card"><span>Comissões estimadas</span><strong><?= $money($commissionTotal) ?></strong><small>Calculadas pela comissão de cada afiliado</small></article><article class="stat-card"><span>Afiliados com vendas</span><strong><?= count(array_filter($affiliates,static fn($a)=>(float)$a['sales']>0)) ?></strong><small>Com faturamento acima de zero</small></article><article class="stat-card"><span>Vendas recebidas da Kiwify</span><strong><?= $money(((int)$kiwifyStats['approved_cents'])/100) ?></strong><small><?= (int)$kiwifyStats['orders'] ?> pedidos registrados · estornos: <?= $money(((int)$kiwifyStats['refunded_cents'])/100) ?></small></article></section>
<section class="panel"><form class="filters" method="get"><label class="search">⌕ <input name="q" value="<?= se($search) ?>" placeholder="Buscar afiliado, e-mail ou código"></label><select name="group" aria-label="Filtrar por grupo"><option value="all">Todos os grupos</option><?php foreach($groups as $group): ?><option value="<?= se($group) ?>" <?= $groupFilter===$group?'selected':'' ?>><?= se($group) ?></option><?php endforeach; ?></select><select name="status" aria-label="Filtrar por status"><option value="all">Todos os status</option><option value="active" <?= $statusFilter==='active'?'selected':'' ?>>Ativos</option><option value="pending" <?= $statusFilter==='pending'?'selected':'' ?>>Pendentes</option><option value="inactive" <?= $statusFilter==='inactive'?'selected':'' ?>>Inativos</option></select><button class="button" type="submit">Aplicar filtros</button></form>
<div class="table-scroll"><table id="salesTable"><thead><tr><th>Afiliado</th><th>Grupo</th><th>Pedidos</th><th>Faturamento</th><th>Comissão</th><th>Comissão estimada</th><th>Status</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="7" class="empty">Nenhum resultado encontrado.</td></tr><?php endif; ?>
<?php foreach($rows as $a): $commission=(float)$a['sales']*(float)$a['commission']/100; $initials=affiliate_initials((string)$a['name']); $status=['active'=>'Ativo','pending'=>'Pendente','inactive'=>'Inativo'][$a['status']]??'Ativo'; ?><tr><td><span class="person"><i class="avatar"><?= se($initials) ?></i><span><b><?= se($a['name']) ?></b><small><?= se($a['email']) ?></small></span></span></td><td><?= se($a['group']) ?></td><td><?= number_format((int)$a['orders'],0,',','.') ?></td><td class="money"><?= $money($a['sales']) ?></td><td><?= se($a['commission']) ?>%</td><td class="money"><?= $money($commission) ?></td><td><span class="status <?= se($a['status']) ?>"><?= se($status) ?></span></td></tr><?php endforeach; ?>
</tbody></table></div></section>
<section class="panel order-panel"><div class="panel-heading"><div><h2>Vendas recebidas por integração</h2><p>Até 50 vendas recentes, somente de produtos autorizados e afiliados vinculados.</p></div><a href="integrations.php">Ver integrações →</a></div><div class="table-scroll"><table><thead><tr><th>Transação</th><th>Produto</th><th>Data</th><th>Afiliado</th><th>Origem</th><th>Valor</th><th>Comissão</th><th>Status</th></tr></thead><tbody><?php if(!$integratedOrders): ?><tr><td colspan="8" class="empty">Nenhuma venda integrada ainda. Autorize produtos e vincule afiliados em Integrações.</td></tr><?php endif; ?><?php foreach($integratedOrders as $order): ?><tr><td><code><?= se($order['external_order_id']) ?></code></td><td><?= se($order['product_name'] ?: ('ID '.$order['external_product_id'])) ?></td><td><?= se(date('d/m/Y H:i',strtotime($order['sold_at']))) ?></td><td><?= se($order['affiliate_name']?:'Sem atribuição') ?></td><td><?= se($order['connection_name']) ?></td><td class="money"><?= $money($order['amount_cents']/100) ?></td><td class="money"><?= $order['commission_cents']===null?'—':$money($order['commission_cents']/100) ?></td><td><span class="status <?= $order['status']==='approved'?'active':'inactive' ?>"><?= ['approved'=>'Aprovada','pending'=>'Pendente','refunded'=>'Reembolsada','canceled'=>'Cancelada'][$order['status']]??se(ucfirst($order['status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section><p class="note">As comissões recebidas da plataforma ficam registradas por transação; quando o webhook não informa o valor, o AFFILIEY calcula pelo percentual do afiliado.</p></main></body></html>
