<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';require_once __DIR__ . '/../modules/community-groups.php';require_login();
$user=current_user();if(($user['active_profile']??'')!=='affiliate'){header('Location: dashboard.php');exit;}
$groups=community_group_list_for_student((string)$user['id']);$feed=[];
foreach($groups as $group){if($group['membership_status']!=='active')continue;$rows=community_resource_list_for_student((string)$group['tenant_id'],(string)$group['id'],(string)$user['id']);foreach($rows as $row)$feed[]=[...$row,'group_name'=>$group['name'],'producer_name'=>$group['producer_name']];}
usort($feed,static fn($a,$b)=>strcmp((string)($b['starts_at']??$b['created_at']),(string)($a['starts_at']??$a['created_at'])));
function sc_e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conteúdos dos grupos — AFFILIEY</title><link rel="stylesheet" href="/assets/css/app-theme.css?v=3"><link rel="stylesheet" href="/assets/css/brand.css?v=affiliey4"><link rel="stylesheet" href="/assets/css/workspace-premium.css?v=3"><link rel="stylesheet" href="/assets/css/profile-environments.css?v=3"><link rel="stylesheet" href="/assets/css/typography.css?v=1"></head><body class="app-shell affiliate-portal"><header class="topbar"><a class="brand" href="student-dashboard.php"><img class="brand-logo" src="/brand/affiliey-logo-dark.png" alt="AFFILIEY"></a><nav class="main-nav"><?= app_workspace_navigation() ?></nav><div class="top-actions"><?= app_header_account_tools() ?><span><?= sc_e($user['name']??'') ?></span><a href="login.php?logout=1">Sair</a></div></header><main class="profile-page"><div class="profile-heading"><div><span class="profile-eyebrow">AMBIENTE DO ALUNO</span><h1>Conteúdos dos meus grupos</h1><p>Materiais, comunicados e treinamentos publicados pelos produtores dos grupos em que você participa.</p></div></div><?php if(!$feed): ?><section class="profile-empty"><h2>Nenhum conteúdo disponível ainda</h2><p>Quando os produtores publicarem conteúdos nos seus grupos ativos, eles aparecerão aqui.</p><a class="button" href="student-dashboard.php?view=groups">Ver meus grupos</a></section><?php else: ?><div class="profile-announcements"><?php foreach($feed as $item): ?><article><span><?= sc_e($item['producer_name']) ?> · <?= sc_e($item['group_name']) ?> · <?= sc_e(['content'=>'Conteúdo','announcement'=>'Comunicado','meeting'=>'Reunião'][$item['resource_type']]??$item['resource_type']) ?><?= $item['starts_at']?' · '.sc_e(date('d/m/Y H:i',strtotime($item['starts_at']))):'' ?></span><h3><?= sc_e($item['title']) ?></h3><p><?= nl2br(sc_e($item['body'])) ?></p><?php if($item['resource_url']): ?><a href="<?= sc_e($item['resource_url']) ?>" target="_blank" rel="noopener noreferrer">Abrir conteúdo ↗</a><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?></main></body></html>
