<?php
declare(strict_types=1);
require_once __DIR__ . '/../modules/auth.php';
require_login(); start_app_session();
$user=current_user();$error='';$inviteUrl='';$flash='';$canInvite=in_array((string)$user['role'],['owner','admin'],true);
if(empty($_SESSION['team_csrf']))$_SESSION['team_csrf']=bin2hex(random_bytes(32));$csrf=$_SESSION['team_csrf'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_role(['owner','admin']);
    if(!hash_equals($csrf,(string)($_POST['csrf']??''))){http_response_code(403);exit('Sessão expirada. Atualize a página.');}
    $email=filter_var(trim((string)($_POST['email']??'')),FILTER_VALIDATE_EMAIL);$role=(string)($_POST['role']??'viewer');
    if(!$email||!in_array($role,['admin','manager','viewer'],true))$error='Informe um e-mail válido e um papel permitido.';
    else{try{$token=issue_team_invitation(tenant_id(),(string)$email,$role,(string)$user['id']);$protocol=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https://':'http://';$inviteUrl=$protocol.($_SERVER['HTTP_HOST']??'localhost').'/accept-invitation.php?token='.rawurlencode($token);$flash='Convite criado. Copie o link e envie para a pessoa.';}catch(DomainException $exception){$error=$exception->getMessage();}}
}
$members=tenant_members();$invitations=tenant_invitations();
function te($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$roleNames=['owner'=>'Proprietário','admin'=>'Administrador','manager'=>'Gestor','viewer'=>'Leitura'];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Equipe — Vértice</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/team.css"><script src="assets/js/team.js" defer></script><link rel="stylesheet" href="assets/css/app-theme.css?v=1"></head><body class="app-shell"><header class="topbar"><a class="brand" href="dashboard.php"><span class="brand-mark">v</span> vértice<span class="brand-dot">.</span></a><nav class="main-nav"><a href="dashboard.php">Visão geral</a><a href="affiliates.php">Afiliados</a><a href="sales.php">Vendas</a><a href="campaigns.php">Metas</a><a class="selected" href="team.php">Equipe</a></nav><div class="top-actions"><span><?= te($user['tenant_name']??'') ?></span><a href="login.php?logout=1">Sair</a></div></header><main class="page"><div class="crumb"><a href="dashboard.php">Workspace</a> / Equipe</div><section class="welcome"><div><span class="eyebrow">ESPAÇO DA ORGANIZAÇÃO</span><h1>Equipe e acessos</h1><p>Convide pessoas para trabalhar no espaço <?= te($user['tenant_name']??'') ?>.</p></div></section>
<?php if($flash): ?><div class="notice"><?= te($flash) ?></div><?php endif; ?><?php if($error): ?><div class="notice error"><?= te($error) ?></div><?php endif; ?>
<?php if($inviteUrl): ?><section class="invite-result"><b>Link de convite</b><p>Compartilhe este link com <?= te($_POST['email']??'a pessoa convidada') ?>. Ele expira em 7 dias e só pode ser usado uma vez.</p><div class="copy-row"><input id="inviteLink" readonly value="<?= te($inviteUrl) ?>"><button id="copyInvite" class="button primary" type="button">Copiar link</button></div><small>O envio por e-mail ainda não está configurado.</small></section><?php endif; ?>
<div class="team-layout"><section class="panel"><div class="panel-head"><div><h2>Membros do espaço</h2><p><?= count($members) ?> pessoa(s) com acesso</p></div></div><div class="table-scroll"><table><thead><tr><th>Pessoa</th><th>Papel</th><th>Desde</th></tr></thead><tbody><?php foreach($members as $member): ?><tr><td><b><?= te($member['name']) ?></b><small><?= te($member['email']) ?></small></td><td><span class="role <?= te($member['role']) ?>"><?= te($roleNames[$member['role']]??$member['role']) ?></span></td><td><?= te(date('d/m/Y',strtotime($member['created_at']))) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<aside class="side"><section class="panel"><div class="panel-head"><div><h2>Convidar para equipe</h2><p>O convite vincula a conta a este espaço.</p></div></div><?php if($canInvite): ?><form method="post"><input type="hidden" name="csrf" value="<?= te($csrf) ?>"><label>E-mail<input type="email" name="email" placeholder="pessoa@empresa.com" required></label><label>Papel<select name="role"><option value="manager">Gestor — opera afiliados e campanhas</option><option value="admin">Administrador — gerencia equipe</option><option value="viewer">Leitura — consulta os dados</option></select></label><button class="button primary full" type="submit">Criar convite</button></form><?php else: ?><p class="readonly">Somente proprietários e administradores podem convidar membros.</p><?php endif; ?></section>
<section class="panel"><div class="panel-head"><div><h2>Convites pendentes</h2><p>Expiram após 7 dias</p></div></div><?php if(!$invitations): ?><p class="readonly">Nenhum convite pendente.</p><?php else: foreach($invitations as $inv): ?><div class="pending"><span><b><?= te($inv['email']) ?></b><small><?= te($roleNames[$inv['role']]??'') ?> · expira <?= te(date('d/m',strtotime($inv['expires_at']))) ?></small></span><i>Enviado</i></div><?php endforeach; endif; ?></section></aside></div>
<section class="roles"><h2>Papéis e permissões</h2><div><article><b>Proprietário</b><p>Controle completo do espaço e da equipe.</p></article><article><b>Administrador</b><p>Gerencia equipe, afiliados, vendas e campanhas.</p></article><article><b>Gestor</b><p>Gerencia afiliados, vendas e campanhas.</p></article><article><b>Leitura</b><p>Consulta indicadores sem alterar dados.</p></article></div></section></main></body></html>
